services:
  ml-project:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: music-genre-classifier
    volumes:
      - ..:/app
      - ../data/raw/genres:/app/data/raw/genres
      - ../data/processed:/app/data/processed
      - ../models:/app/models
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true